### ISSUE TITLE
Evaluation data

### ISSUE THREAD

**Issue by chaixinning** [LeonHLJ/FouriScale#5]
The laion-5b data set is too large to download. Could you please share the Laion data you used for evaluation? Thank you very much. In addition, do you have any idea how to download part of Laion?

**Comment by LeonHLJ** [comment]
> The laion-5b data set is too large to download. Could you please share the Laion data you used for evaluation? Thank you very much. In addition, do you have any idea how to download part of Laion?

Thanks for your attention. We utilize the full bulk of LAION-5B, which is internally shared in our cluster. We are unable to download the shared data because of cluster policy restrictions. We appreciate your understanding.
